services:
  - type: web
    name: heart-disease-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODEL_PATH
        value: best_rf_model.pkl
      - key: ENCODER_PATH
        value: label_encoders.pkl
